set nocompatible
filetype off

call plug#begin('~/.vim/plugged')

Plug 'stonebuddha/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'Raimondi/delimitMate'
Plug 'ntpeters/vim-better-whitespace'
Plug 'let-def/vimbufsync'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdcommenter'

Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'
Plug 'w0rp/ale'

Plug 'skywind3000/asyncrun.vim'

Plug 'sheerun/vim-polyglot'
" Plug 'jez/vim-better-sml'

call plug#end()

filetype plugin indent on


set backspace=indent,eol,start
set ruler
set number
set showcmd
set incsearch
set hlsearch
set magic
set ignorecase
set smartcase
set noerrorbells
set novisualbell
set t_vb=
set tm=500
set cursorline
set cursorcolumn
set encoding=utf-8
set ffs=unix,dos,mac
set nobackup
set nowb
set noswapfile
set mouse=a
set shiftwidth=2
set tabstop=2
set so=7
set autoindent
set smartindent

syntax on

let mapleader=','
let g:mapleader=','

noremap <silent> <leader><cr> :noh<cr>

nnoremap <silent> <f2> :AsyncRun -raw pbcopy < "$(VIM_FILEPATH)"<cr>
nnoremap <silent> <f6> :AsyncRun -raw -cwd=$(VIM_FILEDIR) "$(VIM_FILEPATH)"<cr>
nnoremap <f8> :!PATH=/usr/bin /usr/bin/lldb %<<cr>

au Filetype cpp nnoremap <silent> <f9> :AsyncRun g++ -std=c++11 -o "$(VIM_FILEDIR)/$(VIM_FILENOEXT)" -g -Wall -Wextra -Wconversion -DLOCAL "$(VIM_FILEPATH)" && size "$(VIM_FILEDIR)/$(VIM_FILENOEXT)"<cr>


" base16-vim
if filereadable(expand("~/.vimrc_background"))
	let base16colorspace=256
	source ~/.vimrc_background
endif

" hi Comment	cterm=italic
" hi Type			cterm=italic
" hi Keyword	cterm=italic

" vim-airline
" let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#buffer_nr_show=1

" delimitMate
let delimitMate_expand_cr=1

" asyncrun
let g:asyncrun_open=6
nnoremap <f10> :call asyncrun#quickfix_toggle(6)<cr>

" ale
let g:ale_linters_explicit=1
let g:ale_completion_delay=500
let g:ale_echo_delay=20
let g:ale_lint_delay=500
let g:ale_echo_msg_format='[%linter%] %code: %%s'
let g:ale_lint_on_text_changed='normal'
let g:ale_lint_on_insert_leave=1
let g:airline#extensions#ale#enabled=1

let g:ale_linters = {
			\	'cpp': ['clang'],
			\	'ocaml': ['merlin'],
			\	'rust': ['rls'],
			\}
let g:ale_cpp_clang_options='-std=c++11 -stdlib=libc++ -Wall -Wextra -Wconversion'

let g:ale_fix_on_save=1
let g:ale_fixers = {
			\	'cpp': ['clang-format'],
			\	'ocaml': ['ocp-indent'],
			\	'rust': ['rustfmt'],
			\}

let g:ale_sign_error="✘"
let g:ale_sign_warning="▲"
hi! clear SpellBad
hi! clear SpellCap
hi! clear SpellRare
hi! SpellBad gui=undercurl guisp=red
hi! SpellCap gui=undercurl guisp=blue
hi! SpellRare gui=undercurl guisp=magenta

" merlin
let g:opamshare=substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"
execute "set rtp+=" . g:opamshare . "/ocp-indent/vim"

" vim-better-sml
" au FileType sml nnoremap <silent> <buffer> <leader>t :SMLTypeQuery<cr>
" au FileType sml nnoremap <silent> <buffer> gd :SMLJumpToDef<cr>
